# Generated by Django 5.0.7 on 2024-07-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='subway',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
