# Generated by Django 5.0.7 on 2024-07-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_logindetails_subway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetails',
            name='subway',
        ),
    ]
