# Generated by Django 5.0.7 on 2024-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_checkboxmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxmodel',
            name='checkboxName',
            field=models.CharField(default='Emergency_Test', max_length=255),
        ),
    ]
