# Generated by Django 5.0.7 on 2024-07-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_checkboxmodel_checkboxname'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='subwayAccount',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checkboxmodel',
            name='isChecked',
            field=models.BooleanField(default=True),
        ),
    ]
