# Generated by Django 5.0.7 on 2024-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_logindetails_subwayaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxmodel',
            name='isSubwayWlan',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checkboxmodel',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
    ]
