# Generated by Django 5.0.7 on 2024-07-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxmodel',
            name='name',
            field=models.CharField(default='Subway Toggle', max_length=255),
        ),
        migrations.AlterField(
            model_name='checkboxmodel',
            name='isChecked',
            field=models.BooleanField(default=True),
        ),
    ]
