# Generated by Django 5.0.7 on 2024-07-25 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_checkboxmodel_name_alter_checkboxmodel_ischecked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkboxmodel',
            old_name='name',
            new_name='stationName',
        ),
        migrations.RenameField(
            model_name='checkboxmodel',
            old_name='checkboxName',
            new_name='wlanName',
        ),
    ]
