# Generated by Django 5.0.7 on 2024-07-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_rename_name_checkboxmodel_stationname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboxmodel',
            name='isChecked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
