# Generated by Django 5.0.7 on 2024-08-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_alter_checkboxmodel_ischecked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='busAccount',
            field=models.BooleanField(default=True),
        ),
    ]
