# Generated by Django 5.0.7 on 2024-08-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_profile_busaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstTimeLogin',
            field=models.BooleanField(default=True),
        ),
    ]
